version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up:"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
