- id: sync-with-uv
  name: Sync with uv
  description: Automatically sync pre-commit repos and additional dependencies with package versions in uv.lock
  entry: swu
  language: python
  files: uv.lock
